### ISSUE TITLE
API calls

### ISSUE THREAD

**Issue by deadmanIsARabbit** [burnpiro/reveal-drawer#3]
Hi,

just wanted to ask if there are any API calls to toggle the drawer if you dont have a keyboard?
e.g. Bind the Drawer to a button.

**Comment by burnpiro** [comment]
Hi,

As I can see in the reveal.js API there is a public method [`triggerKey` ](https://github.com/hakimel/reveal.js/blob/master/js/reveal.js#L2747) which receives the keyboard's `keyCode` as an argument. It is defined [__here__](https://github.com/hakimel/reveal.js/blob/4fe3946cb43de57f79aaa7b646aee7e78f4bcc75/js/controllers/keyboard.js#L107) and if you set that value to be the same keycode as defined in the plugin it should triger keyboard event for you. You can write it inside custom function that executes on `onclick` button event.

**Comment by deadmanIsARabbit** [comment]
Hi,

thank you very much! This is exactly what i needed.
